/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentprogresstracking;

import com.mongodb.BasicDBList;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author overlord_96
 */
public class ViewDetails extends javax.swing.JFrame {

    /**
     * Creates new form ViewDetails
     */
    
    private String stname,bloodgrp,email,area,city,date,department,division,year;
    private long rollno,mobileno,pincode;
    
    private String fthname,mthname;
    private long fthmobile,mthmobile;
    
    private String activityname,activitydate,achievement,institutename;
    
    private int scr1,scr2,scr3,scr4,scr5;
    
    public ViewDetails() {
        initComponents();
        
    }
    public ViewDetails(long s){
        initComponents();
        rollno = s;
        
        
        try{
            MongoClient client = new MongoClient("localhost", 27017);
            DB db = client.getDB("StudentProgressTracking");
            DBCollection student = db.getCollection("student");
            DBCollection extra = db.getCollection("extracurricular");
            
            DefaultTableModel table = (DefaultTableModel)mentorextratable.getModel();
            
            DBCursor cursor = student.find(new BasicDBObject("_id", rollno));
            for(DBObject obj:cursor){
                stname = (String)obj.get("Name");
                rollno = (long)obj.get("_id");
                department = (String)obj.get("Department");
                division = (String)obj.get("Division");
                year = (String)obj.get("Year");
                bloodgrp = (String)obj.get("BloodGroup");
                mobileno = (long)obj.get("MobileNo");
                email = (String)obj.get("EmailID");
                date = (String)obj.get("DateOfBirth");
                
                DBObject addr = (BasicDBObject)obj.get("Address");
                area = (String)addr.get("Area");
                city = (String)addr.get("City");
                pincode = (long)addr.get("Pincode");
                
                fthname = (String)obj.get("FatherName");
                mthname = (String)obj.get("MotherName");
                fthmobile = (long)obj.get("FatherMobileNo");
                mthmobile = (long)obj.get("MotherMobileNo");
            }
   
            parea.setText(area);
            pblood.setText(bloodgrp);
            pcity.setText(city);
            pdepartment.setText(department);
            pdiv.setText(division);
            pdob.setText(date);
            pemail.setText(email);
            pfathermob.setText(fthmobile+"");
            pfathername.setText(fthname);
            pmothermob.setText(mthmobile+"");
            pmothername.setText(mthname);
            pname.setText(stname);
            ppin.setText(pincode+"");
            prollno.setText(rollno+"");
            pstudentmob.setText(mobileno+"");
            pyear.setText(year);
            
            DBCursor cursorextra = extra.find(new BasicDBObject("Student_ID", rollno));
            for(DBObject obj:cursorextra){
                activityname = (String)obj.get("ActivityName");
                activitydate = (String)obj.get("Date");
                achievement = (String)obj.get("Achievement");
                institutename = (String)obj.get("Institute");
                
                table.addRow(new Object[]{activityname,activitydate,institutename,achievement});
            }

        }
        catch(Exception e){
            e.printStackTrace();
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pdiv = new javax.swing.JLabel();
        pyear = new javax.swing.JLabel();
        prollno = new javax.swing.JLabel();
        pblood = new javax.swing.JLabel();
        pdepartment = new javax.swing.JLabel();
        pfathername = new javax.swing.JLabel();
        pmothername = new javax.swing.JLabel();
        pdob = new javax.swing.JLabel();
        parea = new javax.swing.JLabel();
        ppin = new javax.swing.JLabel();
        pcity = new javax.swing.JLabel();
        pstudentmob = new javax.swing.JLabel();
        pemail = new javax.swing.JLabel();
        pfathermob = new javax.swing.JLabel();
        pname = new javax.swing.JLabel();
        pmothermob = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        feradiobtn = new javax.swing.JRadioButton();
        seradiobtn = new javax.swing.JRadioButton();
        teradiobtn = new javax.swing.JRadioButton();
        beradiobtn = new javax.swing.JRadioButton();
        showmarksbtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mentorextratable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mentee Details");
        setResizable(false);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 28, 50, 17);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RollNO:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(155, 76, 57, 17);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(113, 226, 99, 17);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Division:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(142, 320, 67, 17);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Year:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(167, 271, 42, 17);

        jLabel24.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Blood Group:");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(105, 361, 104, 17);

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("MobileNo:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(581, 28, 78, 17);

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email ID:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(593, 70, 66, 17);

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date of Birth:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(554, 227, 105, 17);

        jLabel20.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Address:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(522, 273, 82, 17);

        jLabel21.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Area:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(616, 273, 43, 17);

        jLabel22.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("City:");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(623, 320, 36, 17);

        jLabel23.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("PinCode:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(588, 359, 71, 17);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Father's Name:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(93, 118, 119, 17);

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mother's Name:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(88, 179, 124, 17);

        jLabel17.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Father's MobileNo:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(510, 127, 149, 17);

        pdiv.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pdiv.setForeground(new java.awt.Color(255, 255, 255));
        pdiv.setText("Label");
        jPanel2.add(pdiv);
        pdiv.setBounds(241, 316, 171, 24);

        pyear.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pyear.setForeground(new java.awt.Color(255, 255, 255));
        pyear.setText("Label");
        jPanel2.add(pyear);
        pyear.setBounds(241, 267, 171, 24);

        prollno.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        prollno.setForeground(new java.awt.Color(255, 255, 255));
        prollno.setText("Label");
        jPanel2.add(prollno);
        prollno.setBounds(240, 72, 171, 24);

        pblood.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pblood.setForeground(new java.awt.Color(255, 255, 255));
        pblood.setText("Label");
        jPanel2.add(pblood);
        pblood.setBounds(241, 357, 171, 24);

        pdepartment.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pdepartment.setForeground(new java.awt.Color(255, 255, 255));
        pdepartment.setText("Label");
        jPanel2.add(pdepartment);
        pdepartment.setBounds(241, 222, 200, 24);

        pfathername.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pfathername.setForeground(new java.awt.Color(255, 255, 255));
        pfathername.setText("Label");
        jPanel2.add(pfathername);
        pfathername.setBounds(240, 114, 220, 24);

        pmothername.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pmothername.setForeground(new java.awt.Color(255, 255, 255));
        pmothername.setText("Label");
        jPanel2.add(pmothername);
        pmothername.setBounds(240, 175, 220, 24);

        pdob.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pdob.setForeground(new java.awt.Color(255, 255, 255));
        pdob.setText("Label");
        jPanel2.add(pdob);
        pdob.setBounds(678, 223, 210, 24);

        parea.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        parea.setForeground(new java.awt.Color(255, 255, 255));
        parea.setText("Label");
        jPanel2.add(parea);
        parea.setBounds(678, 269, 240, 24);

        ppin.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        ppin.setForeground(new java.awt.Color(255, 255, 255));
        ppin.setText("Label");
        jPanel2.add(ppin);
        ppin.setBounds(678, 355, 171, 24);

        pcity.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pcity.setForeground(new java.awt.Color(255, 255, 255));
        pcity.setText("Label");
        jPanel2.add(pcity);
        pcity.setBounds(678, 316, 220, 24);

        pstudentmob.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pstudentmob.setForeground(new java.awt.Color(255, 255, 255));
        pstudentmob.setText("Label");
        jPanel2.add(pstudentmob);
        pstudentmob.setBounds(678, 24, 210, 24);

        pemail.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pemail.setForeground(new java.awt.Color(255, 255, 255));
        pemail.setText("Label");
        jPanel2.add(pemail);
        pemail.setBounds(678, 66, 260, 24);

        pfathermob.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pfathermob.setForeground(new java.awt.Color(255, 255, 255));
        pfathermob.setText("Label");
        jPanel2.add(pfathermob);
        pfathermob.setBounds(678, 123, 250, 24);

        pname.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pname.setForeground(new java.awt.Color(255, 255, 255));
        pname.setText("Label");
        jPanel2.add(pname);
        pname.setBounds(240, 24, 230, 24);

        pmothermob.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        pmothermob.setForeground(new java.awt.Color(255, 255, 255));
        pmothermob.setText("Label");
        jPanel2.add(pmothermob);
        pmothermob.setBounds(678, 180, 200, 24);

        jLabel36.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Mother's MobileNo:");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(506, 184, 152, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/ed9362deab44ad42b136b654470bbf1d.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 460);

        jTabbedPane1.addTab("Personal", jPanel2);

        jPanel3.setLayout(null);

        feradiobtn.setBackground(new Color(0,0,0,0));
        buttonGroup1.add(feradiobtn);
        feradiobtn.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        feradiobtn.setForeground(new java.awt.Color(255, 255, 255));
        feradiobtn.setText("FE");
        feradiobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        feradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feradiobtnActionPerformed(evt);
            }
        });
        jPanel3.add(feradiobtn);
        feradiobtn.setBounds(168, 24, 65, 18);

        seradiobtn.setBackground(new Color(0,0,0,0));
        buttonGroup1.add(seradiobtn);
        seradiobtn.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        seradiobtn.setForeground(new java.awt.Color(255, 255, 255));
        seradiobtn.setText("SE");
        seradiobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(seradiobtn);
        seradiobtn.setBounds(280, 24, 58, 18);

        teradiobtn.setBackground(new Color(0,0,0,0));
        buttonGroup1.add(teradiobtn);
        teradiobtn.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        teradiobtn.setForeground(new java.awt.Color(255, 255, 255));
        teradiobtn.setText("TE");
        teradiobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(teradiobtn);
        teradiobtn.setBounds(407, 24, 46, 18);

        beradiobtn.setBackground(new Color(0,0,0,0));
        buttonGroup1.add(beradiobtn);
        beradiobtn.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        beradiobtn.setForeground(new java.awt.Color(255, 255, 255));
        beradiobtn.setText("BE");
        beradiobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(beradiobtn);
        beradiobtn.setBounds(536, 24, 81, 18);

        showmarksbtn.setBackground(new java.awt.Color(0, 51, 153));
        showmarksbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        showmarksbtn.setForeground(new java.awt.Color(255, 255, 255));
        showmarksbtn.setText("SHOW MARKS");
        showmarksbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showmarksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showmarksbtnActionPerformed(evt);
            }
        });
        jPanel3.add(showmarksbtn);
        showmarksbtn.setBounds(669, 20, 139, 27);

        jPanel6.setBackground(new Color(0,0,51,100));

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SEM-II");

        table2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table2);
        if (table2.getColumnModel().getColumnCount() > 0) {
            table2.getColumnModel().getColumn(0).setResizable(false);
            table2.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel12))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(509, 91, 400, 260);

        jPanel5.setBackground(new Color(0,0,51,100));

        table1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setResizable(false);
            table1.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SEM-I");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(88, 91, 397, 258);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/ed9362deab44ad42b136b654470bbf1d.jpg"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(0, 0, 1010, 460);

        jTabbedPane1.addTab("Academic", jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(985, 462));
        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Activitites Performed");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 21, 300, 42);

        mentorextratable.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        mentorextratable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Date", "Institute Name", "Achievement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mentorextratable);
        if (mentorextratable.getColumnModel().getColumnCount() > 0) {
            mentorextratable.getColumnModel().getColumn(0).setResizable(false);
            mentorextratable.getColumnModel().getColumn(1).setResizable(false);
            mentorextratable.getColumnModel().getColumn(2).setResizable(false);
            mentorextratable.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 81, 810, 282);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/ed9362deab44ad42b136b654470bbf1d.jpg"))); // NOI18N
        jPanel4.add(jLabel13);
        jLabel13.setBounds(0, 0, 1010, 450);

        jTabbedPane1.addTab("Extra-Curricular", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void feradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feradiobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feradiobtnActionPerformed

    private void showmarksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showmarksbtnActionPerformed
        
        try{
            MongoClient client = new MongoClient("localhost", 27017);
            DB db = client.getDB("StudentProgressTracking");
            DBCollection academic = db.getCollection("academics");

            DefaultTableModel t2 = (DefaultTableModel)table1.getModel();
            DefaultTableModel t = (DefaultTableModel)table2.getModel();

            t2.setRowCount(0);
            t.setRowCount(0);

            if(feradiobtn.isSelected()){

                int i=0;

                DBCursor cur1 = academic.find(new BasicDBObject("Student_ID", rollno));

                for (DBObject r:cur1){

                    BasicDBList sub = (BasicDBList)r.get("FE_SEM-I");
                    BasicDBObject[] subarr = sub.toArray(new BasicDBObject[0]);

                    for(BasicDBObject obj:subarr){
                        if(i == 0){
                            scr1 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"M-I",scr1});                   
                        }
                        if(i == 1){
                            scr2 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"Physics",scr2});

                        }
                        if(i == 2){
                            scr3 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"Electrical",scr3});

                        }
                        if(i == 3){
                            scr4 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"Civil",scr4});

                        }
                        if(i == 4){
                            scr5 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"EGR-I",scr5});
                        }
                        i++;
                    }

                }

                DBCursor cur2 = academic.find(new BasicDBObject("Student_ID", rollno));

                i = 0;

                for (DBObject s:cur2){

                    BasicDBList sub = (BasicDBList)s.get("FE_SEM-II");
                    BasicDBObject[] subarr = sub.toArray(new BasicDBObject[0]);



                    for(BasicDBObject obj:subarr){
                        if(i == 0){
                            scr1 = (int)obj.get("Score");
                            t.addRow(new Object[]{"M-II",scr1});                   
                        }
                        if(i == 1){
                            scr2 = (int)obj.get("Score");
                            t.addRow(new Object[]{"Chemistry",scr2});

                        }
                        if(i == 2){
                            scr3 = (int)obj.get("Score");
                            t.addRow(new Object[]{"Mechanics",scr3});

                        }
                        if(i == 3){
                            scr4 = (int)obj.get("Score");
                            t.addRow(new Object[]{"Electronics",scr4});

                        }
                        if(i == 4){
                            scr5 = (int)obj.get("Score");
                            t.addRow(new Object[]{"EGR-II",scr5});
                        }
                        i++;
                    }

                }

            }
            else if(seradiobtn.isSelected()){



                int i=0;

                DBCursor cur1 = academic.find(new BasicDBObject("Student_ID", rollno));

                for (DBObject r:cur1){

                    BasicDBList sub = (BasicDBList)r.get("SE_SEM-I");
                    BasicDBObject[] subarr = sub.toArray(new BasicDBObject[0]);

                    for(BasicDBObject obj:subarr){
                        if(i == 0){
                            scr1 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"DS",scr1});                   
                        }
                        if(i == 1){
                            scr2 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"DSPS",scr2});

                        }
                        if(i == 2){
                            scr3 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"DELD",scr3});

                        }
                        if(i == 3){
                            scr4 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"OSA",scr4});

                        }
                        if(i == 4){
                            scr5 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"MA",scr5});
                        }
                        i++;
                    }

                }

                DBCursor cur2 = academic.find(new BasicDBObject("Student_ID", rollno));

                i = 0;

                for (DBObject s:cur2){

                    BasicDBList sub = (BasicDBList)s.get("SE_SEM-II");
                    BasicDBObject[] subarr = sub.toArray(new BasicDBObject[0]);

                    for(BasicDBObject obj:subarr){
                        if(i == 0){
                            scr1 = (int)obj.get("Score");
                            t.addRow(new Object[]{"M-III",scr1});                   
                        }
                        if(i == 1){
                            scr2 = (int)obj.get("Score");
                            t.addRow(new Object[]{"OOMP",scr2});

                        }
                        if(i == 2){
                            scr3 = (int)obj.get("Score");
                            t.addRow(new Object[]{"MIT",scr3});

                        }
                        if(i == 3){
                            scr4 = (int)obj.get("Score");
                            t.addRow(new Object[]{"CGG",scr4});

                        }
                        if(i == 4){
                            scr5 = (int)obj.get("Score");
                            t.addRow(new Object[]{"CO",scr5});
                        }
                        i++;
                    }

                }

            }
            else if(teradiobtn.isSelected()){



                int i=0;

                DBCursor cur1 = academic.find(new BasicDBObject("Student_ID", rollno));

                for (DBObject r:cur1){

                    BasicDBList sub = (BasicDBList)r.get("TE_SEM-I");
                    BasicDBObject[] subarr = sub.toArray(new BasicDBObject[0]);

                    for(BasicDBObject obj:subarr){
                        if(i == 0){
                            scr1 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"TOC",scr1});                   
                        }
                        if(i == 1){
                            scr2 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"DCWSN",scr2});

                        }
                        if(i == 2){
                            scr3 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"CF&CA",scr3});

                        }
                        if(i == 3){
                            scr4 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"DBMSA",scr4});

                        }
                        if(i == 4){
                            scr5 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"OSD",scr5});
                        }
                        i++;
                    }

                }

                DBCursor cur2 = academic.find(new BasicDBObject("Student_ID", rollno));

                i = 0;

                for (DBObject s:cur2){

                    BasicDBList sub = (BasicDBList)s.get("TE_SEM-II");
                    BasicDBObject[] subarr = sub.toArray(new BasicDBObject[0]);

                    for(BasicDBObject obj:subarr){
                        if(i == 0){
                            scr1 = (int)obj.get("Score");
                            t.addRow(new Object[]{"PCDP",scr1});                   
                        }
                        if(i == 1){
                            scr2 = (int)obj.get("Score");
                            t.addRow(new Object[]{"EOS",scr2});

                        }
                        if(i == 2){
                            scr3 = (int)obj.get("Score");
                            t.addRow(new Object[]{"Computer Network",scr3});

                        }
                        if(i == 3){
                            scr4 = (int)obj.get("Score");
                            t.addRow(new Object[]{"Software Eng.",scr4});

                        }
                        if(i == 4){
                            scr5 = (int)obj.get("Score");
                            t.addRow(new Object[]{"DSPA",scr5});
                        }
                        i++;
                    }

                }
            }
            else if(beradiobtn.isSelected()){



                int i=0;

                DBCursor cur1 = academic.find(new BasicDBObject("Student_ID", rollno));

                for (DBObject r:cur1){

                    BasicDBList sub = (BasicDBList)r.get("BE_SEM-I");
                    BasicDBObject[] subarr = sub.toArray(new BasicDBObject[0]);

                    for(BasicDBObject obj:subarr){
                        if(i == 0){
                            scr1 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"Image Processing",scr1});                   
                        }
                        if(i == 1){
                            scr2 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"CNDM",scr2});

                        }
                        if(i == 2){
                            scr3 = (int)obj.get("CF&CA");
                            t2.addRow(new Object[]{"Advanced Computer Programing",scr3});

                        }
                        if(i == 3){
                            scr4 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"Data Mining tech. and Applications",scr4});

                        }
                        if(i == 4){
                            scr5 = (int)obj.get("Score");
                            t2.addRow(new Object[]{"Embedded Security",scr5});
                        }
                        i++;
                    }

                }

                DBCursor cur2 = academic.find(new BasicDBObject("Student_ID", rollno));

                i = 0;

                for (DBObject s:cur2){

                    BasicDBList sub = (BasicDBList)s.get("BE_SEM-II");
                    BasicDBObject[] subarr = sub.toArray(new BasicDBObject[0]);

                    for(BasicDBObject obj:subarr){
                        if(i == 0){
                            scr1 = (int)obj.get("Score");
                            t.addRow(new Object[]{"Mobile Computing",scr1});                   
                        }
                        if(i == 1){
                            scr2 = (int)obj.get("Score");
                            t.addRow(new Object[]{"Web Technology",scr2});

                        }
                        if(i == 2){
                            scr3 = (int)obj.get("Score");
                            t.addRow(new Object[]{"Cloud Computing",scr3});

                        }
                        if(i == 3){
                            scr4 = (int)obj.get("Score");
                            t.addRow(new Object[]{"Cyber Security",scr4});

                        }
                        if(i == 4){
                            scr5 = (int)obj.get("Score");
                            t.addRow(new Object[]{"Mobile Applications",scr5});
                        }
                        i++;
                    }

                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Please specify the Year", "Oops", JOptionPane.ERROR_MESSAGE);
            }
        
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_showmarksbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton beradiobtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton feradiobtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable mentorextratable;
    private javax.swing.JLabel parea;
    private javax.swing.JLabel pblood;
    private javax.swing.JLabel pcity;
    private javax.swing.JLabel pdepartment;
    private javax.swing.JLabel pdiv;
    private javax.swing.JLabel pdob;
    private javax.swing.JLabel pemail;
    private javax.swing.JLabel pfathermob;
    private javax.swing.JLabel pfathername;
    private javax.swing.JLabel pmothermob;
    private javax.swing.JLabel pmothername;
    private javax.swing.JLabel pname;
    private javax.swing.JLabel ppin;
    private javax.swing.JLabel prollno;
    private javax.swing.JLabel pstudentmob;
    private javax.swing.JLabel pyear;
    private javax.swing.JRadioButton seradiobtn;
    private javax.swing.JButton showmarksbtn;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JRadioButton teradiobtn;
    // End of variables declaration//GEN-END:variables
}
