/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentprogresstracking.classes;

import studentprogresstracking.classes.Email;
import com.mongodb.BasicDBList;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.*;
import org.jfree.chart.plot.*;
import org.jfree.data.category.DefaultCategoryDataset;






/**
 *
 * @author overlord_96
 */
public class MentorPage extends javax.swing.JFrame {

    /**
     * Creates new form MentorPage
     */
    
    MentorLogin obj = new MentorLogin();
    private String currentUser;
    
    
    private String mentname,mentdept,mentquali,mentemail;
    private long mentmobile;
    private int mentid;
    
    private long strollno;
    private String stname,email;
    
    private int f1total,f2total,s1total,s2total,t1total,t2total,b1total,b2total;
    
    DefaultTableModel table;
    
    public MentorPage() {
        initComponents();
    }
    public MentorPage(MentorLogin l){
        initComponents();
        obj = l;
        
        currentUser = obj.usrcurrent;
        
        try{
            MongoClient client = new MongoClient("localhost", 27017);
            DB db = client.getDB("StudentProgressTracking");
            DBCollection mentor = db.getCollection("mentor");
            DBCollection student = db.getCollection("student");
    
            table = (DefaultTableModel)menteestable.getModel();

            DBCursor cursor = mentor.find(new BasicDBObject("Email_ID", currentUser));
            for(DBObject obj:cursor){
                mentname = (String)obj.get("Mentor_name");
                mentid = (int)obj.get("Mentor_ID");
                mentdept = (String)obj.get("Department_name");
                mentemail = (String)obj.get("Email_ID");
                mentmobile = (long)obj.get("Phone_no");
                mentquali = (String)obj.get("Qualification");   
            }
   
            mentordepartment.setText(mentdept);
            mentoremail.setText(mentemail);
            mentorid.setText(mentid+"");
            mentormobile.setText(mentmobile+"");
            mentorname.setText(mentname);
            mentorqualification.setText(mentquali);
            
            DBCursor cursorextra = student.find(new BasicDBObject("Mentor_ID", mentid));
            for(DBObject obj:cursorextra){
                stname = (String)obj.get("Name");
                strollno = (long)obj.get("_id");
                
                table.addRow(new Object[]{strollno,stname});
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mentorid = new javax.swing.JLabel();
        mentorname = new javax.swing.JLabel();
        mentorqualification = new javax.swing.JLabel();
        mentormobile = new javax.swing.JLabel();
        mentoremail = new javax.swing.JLabel();
        mentordepartment = new javax.swing.JLabel();
        signoutbtn = new javax.swing.JButton();
        changepasswdbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menteestable = new javax.swing.JTable();
        menteeviewbtn = new javax.swing.JButton();
        mentormeetdate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        sendmailbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setPreferredSize(new java.awt.Dimension(984, 436));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mentor ID:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(140, 90, 120, 24);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile No:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 210, 120, 24);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(180, 130, 80, 24);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Qualification:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(110, 170, 116, 24);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email-ID:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(160, 250, 100, 24);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Department:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 290, 130, 24);

        mentorid.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        mentorid.setForeground(new java.awt.Color(255, 255, 255));
        mentorid.setText("jLabel5");
        jPanel2.add(mentorid);
        mentorid.setBounds(260, 90, 440, 24);

        mentorname.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        mentorname.setForeground(new java.awt.Color(255, 255, 255));
        mentorname.setText("jLabel5");
        jPanel2.add(mentorname);
        mentorname.setBounds(260, 130, 440, 24);

        mentorqualification.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        mentorqualification.setForeground(new java.awt.Color(255, 255, 255));
        mentorqualification.setText("jLabel5");
        jPanel2.add(mentorqualification);
        mentorqualification.setBounds(260, 170, 440, 24);

        mentormobile.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        mentormobile.setForeground(new java.awt.Color(255, 255, 255));
        mentormobile.setText("jLabel5");
        jPanel2.add(mentormobile);
        mentormobile.setBounds(260, 210, 440, 24);

        mentoremail.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        mentoremail.setForeground(new java.awt.Color(255, 255, 255));
        mentoremail.setText("jLabel5");
        jPanel2.add(mentoremail);
        mentoremail.setBounds(260, 250, 440, 24);

        mentordepartment.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        mentordepartment.setForeground(new java.awt.Color(255, 255, 255));
        mentordepartment.setText("jLabel5");
        jPanel2.add(mentordepartment);
        mentordepartment.setBounds(260, 290, 440, 24);

        signoutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutbtnActionPerformed(evt);
            }
        });
        jPanel2.add(signoutbtn);
        signoutbtn.setBounds(880, 10, 81, 27);

        changepasswdbtn.setBackground(new java.awt.Color(0, 51, 153));
        changepasswdbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        changepasswdbtn.setForeground(new java.awt.Color(255, 255, 255));
        changepasswdbtn.setText("Change Password");
        changepasswdbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changepasswdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepasswdbtnActionPerformed(evt);
            }
        });
        jPanel2.add(changepasswdbtn);
        changepasswdbtn.setBounds(640, 10, 210, 27);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/ed9362deab44ad42b136b654470bbf1d.jpg"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 1020, 460);

        jTabbedPane1.addTab("PROFILE", jPanel2);

        jPanel3.setLayout(null);

        menteestable.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        menteestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rollno", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menteestable.setRowSelectionAllowed(false);
        menteestable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(menteestable);
        if (menteestable.getColumnModel().getColumnCount() > 0) {
            menteestable.getColumnModel().getColumn(0).setResizable(false);
            menteestable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(18, 27, 659, 355);

        menteeviewbtn.setBackground(new java.awt.Color(0, 51, 153));
        menteeviewbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        menteeviewbtn.setForeground(new java.awt.Color(255, 255, 255));
        menteeviewbtn.setText("View Details");
        menteeviewbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menteeviewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menteeviewbtnActionPerformed(evt);
            }
        });
        jPanel3.add(menteeviewbtn);
        menteeviewbtn.setBounds(730, 30, 150, 25);

        mentormeetdate.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.add(mentormeetdate);
        mentormeetdate.setBounds(730, 120, 210, 22);

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("New Meeting Date:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(730, 90, 160, 19);

        sendmailbtn.setBackground(new java.awt.Color(0, 51, 153));
        sendmailbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        sendmailbtn.setForeground(new java.awt.Color(255, 255, 255));
        sendmailbtn.setText("SEND E-MAIL");
        sendmailbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendmailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmailbtnActionPerformed(evt);
            }
        });
        jPanel3.add(sendmailbtn);
        sendmailbtn.setBounds(730, 160, 140, 25);

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Progress");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(730, 230, 170, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/ed9362deab44ad42b136b654470bbf1d.jpg"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(0, 0, 1010, 470);

        jTabbedPane1.addTab("MENTEES", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menteeviewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menteeviewbtnActionPerformed
        try{
            long temp1=(long)table.getValueAt(menteestable.getSelectedRow(),menteestable.getSelectedColumn());
            
            new ViewDetails(temp1).setVisible(true);
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Please select a RollNo", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        catch(ClassCastException e){
            JOptionPane.showMessageDialog(this, "Please select a RollNo", "Oops", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menteeviewbtnActionPerformed

    private void sendmailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmailbtnActionPerformed
        
        try{
            MongoClient client = new MongoClient("localhost", 27017);
            DB db = client.getDB("StudentProgressTracking");
            DBCollection student = db.getCollection("student");
            DBCollection mentor = db.getCollection("mentor");
            
            long temp1=(long)table.getValueAt(menteestable.getSelectedRow(),menteestable.getSelectedColumn());
            DBCursor cur = student.find(new BasicDBObject("_id", temp1));

            String date = ((JTextField)mentormeetdate.getDateEditor().getUiComponent()).getText();

            for(DBObject obj:cur){
                email = (String)obj.get("EmailID");
            }
            Email obj = new Email();
            obj.mail1(email,date);
            mentor.update(new BasicDBObject("Email_ID", currentUser), new BasicDBObject("$set", new BasicDBObject("MentorMeetDate", date)));
            
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Please select a RollNo", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        catch(ClassCastException e){
            JOptionPane.showMessageDialog(this, "Please select a RollNo", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_sendmailbtnActionPerformed

    private void signoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutbtnActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Do you really want to sign out?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);    
        if(choice == 0){   
            new MentorLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_signoutbtnActionPerformed

    private void changepasswdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswdbtnActionPerformed
        String passw = JOptionPane.showInputDialog(this, "Enter new password", "New Password",JOptionPane.INFORMATION_MESSAGE);
        if(!(passw == null)){
            MongoClient client = new MongoClient("localhost", 27017);
            DB db = client.getDB("StudentProgressTracking");
            DBCollection mentor = db.getCollection("mentor");
            
            mentor.update(new BasicDBObject("Email_ID", currentUser), new BasicDBObject("$set", new BasicDBObject("password", passw)));
        }
            //System.out.println(passw);
        
    }//GEN-LAST:event_changepasswdbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            long temp1=(long)table.getValueAt(menteestable.getSelectedRow(),menteestable.getSelectedColumn());
            
            //new ViewDetails(temp1).setVisible(true);
        
        
        MongoClient client = new MongoClient("localhost", 27017);
        DB db = client.getDB("StudentProgressTracking");
        DBCollection academic = db.getCollection("academics");
        
        DBCursor cur = academic.find(new BasicDBObject("Student_ID", temp1));
        for(DBObject obj:cur){
            f1total = (int)obj.get("FE-SEM-I-total");
            f2total = (int)obj.get("FE-SEM-II-total");
            s1total = (int)obj.get("SE-SEM-I-total");
            s2total = (int)obj.get("SE-SEM-II-total");
            t1total = (int)obj.get("TE-SEM-I-total");
            t2total = (int)obj.get("TE-SEM-II-total");
            b1total = (int)obj.get("BE-SEM-I-total");
            b2total = (int)obj.get("BE-SEM-II-total");
            
        }
        
        
        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();

        barChartData.setValue(f1total,"Score","FE-SEM-I");
        barChartData.setValue(f2total,"Score","FE-SEM-II");
        barChartData.setValue(s1total,"Score","SE-SEM-I");
        barChartData.setValue(s2total,"Score","SE-SEM-II");
        barChartData.setValue(t1total,"Score","TE-SEM-I");
        barChartData.setValue(t2total,"Score","TE-SEM-II");
        barChartData.setValue(b1total,"Score","BE-SEM-I");
        barChartData.setValue(b2total,"Score","BE-SEM-II");

        JFreeChart barChart=ChartFactory.createBarChart("PROGRESS","SEMESTER","MARKS",barChartData,PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot barchrt=barChart.getCategoryPlot();
        barchrt.setRangeGridlinePaint(Color.BLUE);
                
        //ChartPanel barPanel = new ChartPanel(barChart);
        ChartFrame chartfrm=new ChartFrame("Student Progress Report",barChart,true) ;
        chartfrm.setVisible(true);
        chartfrm.setSize(1920,1080);
        
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Please select a RollNo", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        catch(ClassCastException e){
            JOptionPane.showMessageDialog(this, "Please select a RollNo", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        catch(NullPointerException e){
            DefaultCategoryDataset barChartData = new DefaultCategoryDataset();

            barChartData.setValue(f1total,"Score","FE-SEM-I");
            barChartData.setValue(f2total,"Score","FE-SEM-II");
            barChartData.setValue(s1total,"Score","SE-SEM-I");
            barChartData.setValue(s2total,"Score","SE-SEM-II");
            barChartData.setValue(t1total,"Score","TE-SEM-I");
            barChartData.setValue(t2total,"Score","TE-SEM-II");
            barChartData.setValue(b1total,"Score","BE-SEM-I");
            barChartData.setValue(b2total,"Score","BE-SEM-II");

            JFreeChart barChart=ChartFactory.createBarChart("PROGRESS","SEMESTER","MARKS",barChartData,PlotOrientation.VERTICAL,false,true,false);
            CategoryPlot barchrt=barChart.getCategoryPlot();
            barchrt.setRangeGridlinePaint(Color.BLUE);

            //ChartPanel barPanel = new ChartPanel(barChart);
            ChartFrame chartfrm=new ChartFrame("Student Progress Report",barChart,true) ;
            chartfrm.setVisible(true);
            chartfrm.setSize(1920,1080);
        }        
    }//GEN-LAST:event_jButton1ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MentorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MentorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MentorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MentorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MentorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changepasswdbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable menteestable;
    private javax.swing.JButton menteeviewbtn;
    private javax.swing.JLabel mentordepartment;
    private javax.swing.JLabel mentoremail;
    private javax.swing.JLabel mentorid;
    private com.toedter.calendar.JDateChooser mentormeetdate;
    private javax.swing.JLabel mentormobile;
    private javax.swing.JLabel mentorname;
    private javax.swing.JLabel mentorqualification;
    private javax.swing.JButton sendmailbtn;
    private javax.swing.JButton signoutbtn;
    // End of variables declaration//GEN-END:variables
}
