/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentprogresstracking.classes;


import javax.swing.JTextField;
import com.mongodb.*;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author overlord_96
 */
public class SignUp extends javax.swing.JFrame {

    
    private String stname,bloodgrp,password,email,area,city,date,department,division,year,confirmpassword;
    private long rollno,mobileno,pincode;
    
    private static long signupcount=0;
    
    private String fthname,mthname,parentarea,parentcity;
    private long fthmobile,mthmobile,parentpin;
    
    boolean flag = false;
    
    public SignUp() {
        initComponents();
        
        //departmentSelectComboBox.addItem("Mechanical");
        //departmentSelectComboBox.addItem("Civil");
        //departmentSelectComboBox.addItem("Electronics");
        departmentSelectComboBox.addItem("Computer");
        //departmentSelectComboBox.addItem("IT");
        
        divisionComboBox.addItem("A");
        divisionComboBox.addItem("B");
        
        yearComboBox.addItem("FE");
        yearComboBox.addItem("SE");
        yearComboBox.addItem("TE");
        yearComboBox.addItem("BE");
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        studentname = new javax.swing.JTextField();
        studentrollno = new javax.swing.JTextField();
        departmentSelectComboBox = new javax.swing.JComboBox<>();
        divisionComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        savestudentdetailsbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        studentmobile = new javax.swing.JTextField();
        studentemail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        studentarea = new javax.swing.JTextField();
        studentcity = new javax.swing.JTextField();
        studentpincode = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        studentbldgroup = new javax.swing.JTextField();
        studentconfirmpassw = new javax.swing.JPasswordField();
        jLabel27 = new javax.swing.JLabel();
        studentpassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fathername = new javax.swing.JTextField();
        fathermobile = new javax.swing.JTextField();
        addrarea = new javax.swing.JTextField();
        mothername = new javax.swing.JTextField();
        mothermobile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addrcity = new javax.swing.JTextField();
        addrpincode = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        saveparentdetailsbtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        signupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign Up");
        setResizable(false);

        jPanel4.setBackground(new Color(0,0,0,150));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RollNO:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 140, 120, 24);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 100, 90, 24);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Division:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 230, 130, 24);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Year:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 270, 60, 24);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 190, 130, 24);
        jPanel1.add(studentname);
        studentname.setBounds(210, 100, 181, 22);
        jPanel1.add(studentrollno);
        studentrollno.setBounds(210, 140, 181, 22);

        departmentSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentSelectComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(departmentSelectComboBox);
        departmentSelectComboBox.setBounds(210, 190, 110, 22);

        jPanel1.add(divisionComboBox);
        divisionComboBox.setBounds(210, 230, 70, 22);

        jPanel1.add(yearComboBox);
        yearComboBox.setBounds(210, 270, 70, 22);

        savestudentdetailsbtn.setBackground(new java.awt.Color(0, 0, 0));
        savestudentdetailsbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        savestudentdetailsbtn.setForeground(new java.awt.Color(255, 255, 255));
        savestudentdetailsbtn.setText("SAVE");
        savestudentdetailsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savestudentdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savestudentdetailsbtnActionPerformed(evt);
            }
        });
        jPanel1.add(savestudentdetailsbtn);
        savestudentdetailsbtn.setBounds(660, 400, 130, 30);

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("MobileNo:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(560, 100, 140, 24);

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email ID:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(570, 150, 130, 24);
        jPanel1.add(studentmobile);
        studentmobile.setBounds(660, 100, 181, 22);
        jPanel1.add(studentemail);
        studentemail.setBounds(660, 140, 181, 22);

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date of Birth:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(520, 190, 180, 24);

        jLabel17.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("* All fields are mandatory");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 10, 250, 15);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(660, 180, 178, 22);

        jLabel19.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Confirm Pasw:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(60, 400, 150, 24);

        jLabel20.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Address:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(500, 230, 110, 24);

        jLabel21.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Area:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(600, 230, 90, 24);

        jLabel22.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("City:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(610, 270, 90, 24);

        jLabel23.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("PinCode:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(570, 310, 130, 24);
        jPanel1.add(studentarea);
        studentarea.setBounds(660, 230, 130, 22);
        jPanel1.add(studentcity);
        studentcity.setBounds(660, 270, 130, 22);
        jPanel1.add(studentpincode);
        studentpincode.setBounds(660, 310, 140, 22);

        jLabel24.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Blood Group:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(70, 320, 170, 24);
        jPanel1.add(studentbldgroup);
        studentbldgroup.setBounds(210, 320, 72, 22);
        jPanel1.add(studentconfirmpassw);
        studentconfirmpassw.setBounds(210, 400, 180, 22);

        jLabel27.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Password:");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(100, 360, 140, 24);
        jPanel1.add(studentpassword);
        studentpassword.setBounds(210, 360, 180, 22);

        jPanel3.setBackground(new Color(0,0,0,120));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 950, 530);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/w7.jpg"))); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(0, 0, 960, 530);

        jTabbedPane1.addTab("Student Details", jPanel1);

        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Father's Name:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(120, 100, 160, 24);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MobileNo:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(170, 150, 89, 24);

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(130, 190, 73, 24);

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mother's Name:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(460, 100, 138, 24);

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MobileNo:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(520, 150, 89, 24);
        jPanel2.add(fathername);
        fathername.setBounds(280, 100, 160, 22);
        jPanel2.add(fathermobile);
        fathermobile.setBounds(280, 150, 119, 22);
        jPanel2.add(addrarea);
        addrarea.setBounds(280, 190, 119, 22);
        jPanel2.add(mothername);
        mothername.setBounds(640, 100, 180, 22);
        jPanel2.add(mothermobile);
        mothermobile.setBounds(640, 150, 119, 22);

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Area:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(220, 190, 48, 24);

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("City:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(227, 230, 50, 24);

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PinCode:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(190, 270, 100, 24);
        jPanel2.add(addrcity);
        addrcity.setBounds(280, 230, 119, 22);
        jPanel2.add(addrpincode);
        addrpincode.setBounds(280, 270, 119, 22);

        jLabel18.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("* All fields are mandatory");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(20, 10, 250, 15);

        saveparentdetailsbtn.setBackground(new java.awt.Color(0, 0, 0));
        saveparentdetailsbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        saveparentdetailsbtn.setForeground(new java.awt.Color(255, 255, 255));
        saveparentdetailsbtn.setText("SAVE");
        saveparentdetailsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveparentdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveparentdetailsbtnActionPerformed(evt);
            }
        });
        jPanel2.add(saveparentdetailsbtn);
        saveparentdetailsbtn.setBounds(660, 270, 130, 40);

        jPanel5.setBackground(new Color(0,0,0,120));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 0, 950, 500);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/w7.jpg"))); // NOI18N
        jPanel2.add(jLabel26);
        jLabel26.setBounds(0, 0, 960, 520);

        jTabbedPane1.addTab("Parent Details", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 39, Short.MAX_VALUE)))
        );

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar1.setStringPainted(true);

        signupButton.setBackground(new java.awt.Color(0, 0, 0));
        signupButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signupButton.setText("SIGN UP");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(512, 512, 512)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupButton)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void departmentSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentSelectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentSelectComboBoxActionPerformed

    private void savestudentdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savestudentdetailsbtnActionPerformed
        
        try{
            flag = true;
            stname = studentname.getText();
            bloodgrp = studentbldgroup.getText();
            email = studentemail.getText();
            area = studentarea.getText();
            city = studentcity.getText();
            rollno = Long.parseLong(studentrollno.getText());
            //rollno = Integer.parseInt(studentrollno.getText());
            mobileno = Long.parseLong(studentmobile.getText());
            pincode = Long.parseLong(studentpincode.getText());
            department = (String)departmentSelectComboBox.getSelectedItem();
            division = (String)divisionComboBox.getSelectedItem();
            year = (String)yearComboBox.getSelectedItem();
            confirmpassword = (String)studentconfirmpassw.getText();
            password = (String)studentpassword.getText();

            if(!password.equals(confirmpassword)){
                JOptionPane.showMessageDialog(this,"ReEnter the password","Password does not match",JOptionPane.ERROR_MESSAGE);
            }
            
            int length = studentmobile.getText().length();
            if(length > 10 || length < 10)
                throw new NumberFormatException();
            
            length = studentpincode.getText().length();
            if(length > 6 || length < 6)
                throw new NumberFormatException();
            
            length = studentpincode.getText().length();
            if(length > 6 || length < 6)
                throw new NumberFormatException();
            
            if(!email.matches(".*@.*\\.com")){
                JOptionPane.showMessageDialog(this, "Enter vaild email address","Oops",JOptionPane.ERROR_MESSAGE);
                flag = false;
            }
            
            date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
            if(date.equals(""))
                    throw new NumberFormatException();
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please enter valid data in all fields", "Try Again", JOptionPane.ERROR_MESSAGE);
            flag = false;
        }
        if(flag == true)
            jProgressBar1.setValue(50);
    }//GEN-LAST:event_savestudentdetailsbtnActionPerformed

    private void saveparentdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveparentdetailsbtnActionPerformed
        try{
        fthname = fathername.getText();
        mthname = mothername.getText();
        parentarea = addrarea.getText();
        parentcity = addrcity.getText();
        fthmobile = Long.parseLong(fathermobile.getText());
        mthmobile = Long.parseLong(mothermobile.getText());
        parentpin = Long.parseLong(addrpincode.getText());
        
        int length = fathermobile.getText().length();
        if(length > 10 || length < 10)
            throw new NumberFormatException();
        
        length = mothermobile.getText().length();
        if(length > 10 || length < 10)
            throw new NumberFormatException();
        
        length = addrpincode.getText().length();
        if(length > 6 || length < 6)
            throw new NumberFormatException();
 
        if(flag == true)
            jProgressBar1.setValue(100);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please enter valid data in all fields", "Try Again", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveparentdetailsbtnActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        
        if(jProgressBar1.getValue() == 100){
             
            try{
                MongoClient client = new MongoClient("localhost", 27017);
                DB db = client.getDB("StudentProgressTracking");
                DBCollection student = db.getCollection("student");
                
                DBCollection mentor = db.getCollection("mentor");
                
                DBCollection academic = db.getCollection("academics");

                BasicDBObject doc = new BasicDBObject("_id", rollno).append("Name",stname).append("Department",department);
                doc.append("Division",division).append("Year",year).append("BloodGroup",bloodgrp).append("MobileNo", mobileno);
                doc.append("EmailID",email).append("DateOfBirth",date).append("Password",password);

                BasicDBObject address = new BasicDBObject("Area",area).append("City",city).append("Pincode",pincode);
                doc.append("Address",address).append("FatherName",fthname).append("MotherName",mthname);
                doc.append("FatherMobileNo", fthmobile).append("MotherMobileNo",mthmobile);

                BasicDBObject paddress = new BasicDBObject("Area",parentarea).append("City",parentcity).append("Pincode",parentpin);
                doc.append("ParentAddress",paddress);
                
                signupcount = student.count();
                signupcount++;
                
                long mentorId = signupcount%10;
                if(mentorId != 0)
                    doc.append("Mentor_ID",mentorId);
                else{
                    mentorId = (long)10;
                    doc.append("Mentor_ID",mentorId);
                }
                
                student.insert(doc);
                
                mentor.update(new BasicDBObject("Mentor_ID", mentorId), new BasicDBObject("$push", new BasicDBObject("Student_ID", rollno)));
                academic.insert(new BasicDBObject("Student_ID", rollno));
                
                JOptionPane.showMessageDialog(this,"Please login with RollNo as username", "SignUp successfull!", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(DuplicateKeyException e){
                JOptionPane.showMessageDialog(this,"Please check your RollNo", "Invalid Data", JOptionPane.ERROR);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter valid data in all fields", "Try Again", JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                e.printStackTrace();
            }
            
            
            this.setVisible(false);
            this.dispose();
        }
        
    }//GEN-LAST:event_signupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrarea;
    private javax.swing.JTextField addrcity;
    private javax.swing.JTextField addrpincode;
    private javax.swing.JComboBox<String> departmentSelectComboBox;
    private javax.swing.JComboBox<String> divisionComboBox;
    private javax.swing.JTextField fathermobile;
    private javax.swing.JTextField fathername;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mothermobile;
    private javax.swing.JTextField mothername;
    private javax.swing.JButton saveparentdetailsbtn;
    private javax.swing.JButton savestudentdetailsbtn;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField studentarea;
    private javax.swing.JTextField studentbldgroup;
    private javax.swing.JTextField studentcity;
    private javax.swing.JPasswordField studentconfirmpassw;
    private javax.swing.JTextField studentemail;
    private javax.swing.JTextField studentmobile;
    private javax.swing.JTextField studentname;
    private javax.swing.JPasswordField studentpassword;
    private javax.swing.JTextField studentpincode;
    private javax.swing.JTextField studentrollno;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
