/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentprogresstracking.classes;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.Color;
import static java.util.Arrays.asList;
import javax.swing.JOptionPane;

/**
 *
 * @author overlord_96
 */
public class UpdateMarks extends javax.swing.JFrame {

    /**
     * Creates new form Extraupdate
     */
    private long rollno;
    private String year;
    
    private int fm1,fphy,fele,fcivil,fegr1,fm2,fchem,fmechanics,felectronics,fegr2;
    private int sds,sdsps,sdeld,sosa,sma,sm3,soomp,smit,scgg,sco;
    private int ttoc,tdcwsn,tcfca,tdbmsa,tosd,tpcdp,teos,tcn,tsoftware,tdspa;
    private int bimgp,bcndm,bacp,bdmta,bes,bmc,bwt,bcloud,bcs,bma;
    
    private int total;
    
    public UpdateMarks() {
        initComponents();
    }
    public UpdateMarks(long n){
        initComponents();
        rollno = n;
        try{
            MongoClient client = new MongoClient("localhost", 27017);
            DB db = client.getDB("StudentProgressTracking");
            DBCollection student = db.getCollection("student");
            
            DBCursor cursor = student.find(new BasicDBObject("_id", rollno));
            for(DBObject obj:cursor){
                year = (String)obj.get("Year");
            }
        }
        catch(Exception e){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fem1 = new javax.swing.JTextField();
        fephy = new javax.swing.JTextField();
        feelectrical = new javax.swing.JTextField();
        fecivil = new javax.swing.JTextField();
        fegraph1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fesem1updtbtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fem2 = new javax.swing.JTextField();
        fechem = new javax.swing.JTextField();
        femech = new javax.swing.JTextField();
        feelectronics = new javax.swing.JTextField();
        fegraph2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fesem2updtbtn1 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        seds = new javax.swing.JTextField();
        sedsps = new javax.swing.JTextField();
        sedeld = new javax.swing.JTextField();
        seosa = new javax.swing.JTextField();
        sema = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        sesem1updbtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        sem3 = new javax.swing.JTextField();
        seoomp = new javax.swing.JTextField();
        semit = new javax.swing.JTextField();
        secgg = new javax.swing.JTextField();
        seco = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        sesem2updbtn = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tetoc = new javax.swing.JTextField();
        tedcwsn = new javax.swing.JTextField();
        tecfca = new javax.swing.JTextField();
        tedbmsa = new javax.swing.JTextField();
        teosd = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tesem1updbtn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tepcdp = new javax.swing.JTextField();
        teeos = new javax.swing.JTextField();
        tecn = new javax.swing.JTextField();
        tesofte = new javax.swing.JTextField();
        tedspa = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        tesem2updbtn = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        beimgp = new javax.swing.JTextField();
        becndm = new javax.swing.JTextField();
        beacp = new javax.swing.JTextField();
        bedmta = new javax.swing.JTextField();
        bees = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        besem1updbtn = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        bemc = new javax.swing.JTextField();
        bewt = new javax.swing.JTextField();
        becloudc = new javax.swing.JTextField();
        becs = new javax.swing.JTextField();
        bema = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        besem2updbtn = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(null);

        jPanel6.setBackground(new Color(51,0,0,150));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Eng. Mathematics I");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Eng. Physics");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Electrical");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Civil");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Eng. Graphics I");

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SEM I");

        fesem1updtbtn.setBackground(new java.awt.Color(102, 0, 0));
        fesem1updtbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        fesem1updtbtn.setForeground(new java.awt.Color(255, 255, 255));
        fesem1updtbtn.setText("UPDATE");
        fesem1updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fesem1updtbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fem1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fegraph1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fecivil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(feelectrical, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fephy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(fesem1updtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel11)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fephy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(feelectrical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fecivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fegraph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(fesem1updtbtn)
                .addGap(45, 45, 45))
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(50, 0, 0, 450);

        jPanel7.setBackground(new Color(51,0,0,150));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Eng.Mathematics II");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Eng. Chemistry");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Eng. Mechanics");

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Electronics");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Eng. Graphics II");

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SEM II");

        fesem2updtbtn1.setBackground(new java.awt.Color(102, 0, 0));
        fesem2updtbtn1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        fesem2updtbtn1.setForeground(new java.awt.Color(255, 255, 255));
        fesem2updtbtn1.setText("UPDATE");
        fesem2updtbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fesem2updtbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(170, 170, 170))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fesem2updtbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fem2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(femech, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(feelectronics, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fegraph2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 134, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fechem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(femech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(feelectronics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fegraph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(fesem2updtbtn1)
                .addGap(42, 42, 42))
        );

        jPanel2.add(jPanel7);
        jPanel7.setBounds(521, -3, 0, 450);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/bigstock-Old-grunge-brick-wall-backgrou-47476903.jpg"))); // NOI18N
        jPanel2.add(jLabel49);
        jLabel49.setBounds(0, 0, 1040, 490);

        jTabbedPane1.addTab("FE", jPanel2);

        jPanel3.setLayout(null);

        jPanel8.setBackground(new Color(51,0,0,150));

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Discrete Structure");

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DSPS");

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DELD");

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("OSA");

        jLabel17.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MA");

        jLabel18.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("SEM I");

        sesem1updbtn.setBackground(new java.awt.Color(102, 0, 0));
        sesem1updbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        sesem1updbtn.setForeground(new java.awt.Color(255, 255, 255));
        sesem1updbtn.setText("UPDATE");
        sesem1updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesem1updbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel18))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sesem1updbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seds, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sema, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seosa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sedeld, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sedsps, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(seds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sedsps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(sedeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(seosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(sema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(sesem1updbtn)
                .addGap(39, 39, 39))
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(70, 0, 0, 450);

        jPanel9.setBackground(new Color(51,0,0,150));

        jLabel19.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Eng. Mathematics III");

        jLabel20.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("OOMP");

        jLabel21.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MIT");

        jLabel22.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("CGG");

        jLabel23.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("CO");

        jLabel24.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("SEM II");

        sesem2updbtn.setBackground(new java.awt.Color(102, 0, 0));
        sesem2updbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        sesem2updbtn.setForeground(new java.awt.Color(255, 255, 255));
        sesem2updbtn.setText("UPDATE");
        sesem2updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesem2updbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sem3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seoomp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secgg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(sesem2updbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(173, 173, 173))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(sem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(seoomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(semit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(secgg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(seco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(sesem2updbtn)
                .addGap(39, 39, 39))
        );

        jPanel3.add(jPanel9);
        jPanel9.setBounds(530, 0, 0, 450);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/bigstock-Old-grunge-brick-wall-backgrou-47476903.jpg"))); // NOI18N
        jPanel3.add(jLabel50);
        jLabel50.setBounds(0, 0, 1030, 490);

        jTabbedPane1.addTab("SE", jPanel3);

        jPanel4.setLayout(null);

        jPanel10.setBackground(new Color(51,0,0,150));

        jLabel25.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("TOC");

        jLabel26.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("DCWSN");

        jLabel27.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("CFCA");

        jLabel28.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("DBMSA");

        jLabel29.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("OSD");

        jLabel30.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("SEM I");

        tesem1updbtn.setBackground(new java.awt.Color(102, 0, 0));
        tesem1updbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        tesem1updbtn.setForeground(new java.awt.Color(255, 255, 255));
        tesem1updbtn.setText("UPDATE");
        tesem1updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesem1updbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tetoc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teosd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tedbmsa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tecfca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tedcwsn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(tesem1updbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel30)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tetoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tedcwsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tecfca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tedbmsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(teosd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(tesem1updbtn)
                .addGap(38, 38, 38))
        );

        jPanel4.add(jPanel10);
        jPanel10.setBounds(50, 0, 0, 450);

        jPanel11.setBackground(new Color(51,0,0,150));

        jLabel31.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("PCDP");

        jLabel32.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("EOS");

        jLabel33.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Computer Network");

        jLabel34.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Software Eng.");

        jLabel35.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("DSPA");

        jLabel36.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("SEM II");

        tesem2updbtn.setBackground(new java.awt.Color(102, 0, 0));
        tesem2updbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        tesem2updbtn.setForeground(new java.awt.Color(255, 255, 255));
        tesem2updbtn.setText("UPDATE");
        tesem2updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesem2updbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tepcdp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teeos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tecn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tesofte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tedspa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(171, 171, 171))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(tesem2updbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tepcdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(teeos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tecn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tesofte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tedspa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(tesem2updbtn)
                .addGap(38, 38, 38))
        );

        jPanel4.add(jPanel11);
        jPanel11.setBounds(530, -10, 430, 460);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/bigstock-Old-grunge-brick-wall-backgrou-47476903.jpg"))); // NOI18N
        jPanel4.add(jLabel51);
        jLabel51.setBounds(0, 0, 1030, 490);

        jTabbedPane1.addTab("TE", jPanel4);

        jPanel5.setLayout(null);

        jPanel12.setBackground(new Color(51,0,0,150));

        jLabel37.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Image Processing");

        jLabel38.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("CNDM");

        jLabel39.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Advanced Computer Programming");

        jLabel40.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Data Mining Techniques and Applications");

        jLabel41.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Embedded Security");

        jLabel42.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("SEM I");

        besem1updbtn.setBackground(new java.awt.Color(102, 0, 0));
        besem1updbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        besem1updbtn.setForeground(new java.awt.Color(255, 255, 255));
        besem1updbtn.setText("UPDATE");
        besem1updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                besem1updbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel40)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38)
                            .addComponent(jLabel37)
                            .addComponent(besem1updbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beimgp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bees, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bedmta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beacp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(becndm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel42)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(beimgp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(becndm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(beacp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(bedmta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(bees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(besem1updbtn)
                .addGap(38, 38, 38))
        );

        jPanel5.add(jPanel12);
        jPanel12.setBounds(60, 0, 0, 450);

        jPanel13.setBackground(new Color(51,0,0,150));

        jLabel43.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Mobile Computing");

        jLabel44.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Web Technology");

        jLabel45.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Cloud Computing");

        jLabel46.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Cyber Security");

        jLabel47.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Mobile Applications");

        jLabel48.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("SEM II");

        besem2updbtn.setBackground(new java.awt.Color(102, 0, 0));
        besem2updbtn.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        besem2updbtn.setForeground(new java.awt.Color(255, 255, 255));
        besem2updbtn.setText("UPDATE");
        besem2updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                besem2updbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel46)
                            .addComponent(jLabel45)
                            .addComponent(jLabel44)
                            .addComponent(jLabel43))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bemc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(becloudc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(becs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bema, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bewt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(besem2updbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel48)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel48)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(bemc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(bewt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(becloudc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(becs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(bema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(besem2updbtn)
                .addGap(34, 34, 34))
        );

        jPanel5.add(jPanel13);
        jPanel13.setBounds(540, -4, 0, 450);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentprogresstracking/bigstock-Old-grunge-brick-wall-backgrou-47476903.jpg"))); // NOI18N
        jPanel5.add(jLabel52);
        jLabel52.setBounds(0, 0, 1030, 480);

        jTabbedPane1.addTab("BE", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fesem1updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fesem1updtbtnActionPerformed
        
        if(year.equals("FE") || year.equals("SE") || year.equals("TE") || year.equals("BE")){
            try{
                MongoClient client = new MongoClient("localhost", 27017);
                DB db = client.getDB("StudentProgressTracking");
                DBCollection academic = db.getCollection("academics");

                fcivil = Integer.parseInt(fecivil.getText());
                fm1 = Integer.parseInt(fem1.getText());          
                fele = Integer.parseInt(feelectrical.getText());            
                fegr1 = Integer.parseInt(fegraph1.getText());      
                fphy = Integer.parseInt(fephy.getText());
                
                total = fm1+fphy+fele+fcivil+fegr1;
                
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("FE_SEM-I", asList(new BasicDBObject("Subject_name","MI").append("Score", fm1),new BasicDBObject("Subject_name", "Physics").append("Score", fphy), 
                        new BasicDBObject("Subject_name", "Electrical").append("Score", fele), new BasicDBObject("Subject_name", "Civil").append("Score", fcivil)
                        , new BasicDBObject("Subject_name", "EGR-I").append("Score", fegr1)))));
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("FE-SEM-I-total",total )));
                JOptionPane.showMessageDialog(this, "Marks Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter valid data in all fields", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_fesem1updtbtnActionPerformed

    private void sesem1updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesem1updbtnActionPerformed
        
        if(year.equals("BE") || year.equals("SE") || year.equals("TE")){
            try{
                MongoClient client = new MongoClient("localhost", 27017);
                DB db = client.getDB("StudentProgressTracking");
                DBCollection academic = db.getCollection("academics");


                sdeld = Integer.parseInt(sedeld.getText());
                sds = Integer.parseInt(seds.getText());
                sdsps = Integer.parseInt(sedsps.getText());
                sosa = Integer.parseInt(seosa.getText());
                sma = Integer.parseInt(sema.getText());
                total = sds+sdsps+sdeld+sosa+sma;
                
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("SE_SEM-I", asList(new BasicDBObject("Subject_name","DS").append("Score", sds),new BasicDBObject("Subject_name", "DSPS").append("Score", sdsps), 
                        new BasicDBObject("Subject_name", "DELD").append("Score", sdeld), new BasicDBObject("Subject_name", "OSA").append("Score", sosa)
                        , new BasicDBObject("Subject_name", "MA").append("Score", sma)))));
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("SE-SEM-I-total",total )));

                JOptionPane.showMessageDialog(this, "Marks Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter valid data in all fields", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        }
        else
            JOptionPane.showMessageDialog(this, "Invalid operation", "Invalid Operation", JOptionPane.ERROR_MESSAGE);
        
        
    }//GEN-LAST:event_sesem1updbtnActionPerformed

    private void tesem1updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesem1updbtnActionPerformed
        
        if(year.equals("BE") || year.equals("TE")){
            try{
                MongoClient client = new MongoClient("localhost", 27017);
                DB db = client.getDB("StudentProgressTracking");
                DBCollection academic = db.getCollection("academics");

                tcfca = Integer.parseInt(tecfca.getText());
                tdbmsa = Integer.parseInt(tedbmsa.getText());
                tdcwsn = Integer.parseInt(tedcwsn.getText());
                tosd = Integer.parseInt(teosd.getText());
                ttoc = Integer.parseInt(tetoc.getText());
                total = tcfca+tdbmsa+tdcwsn+tosd+ttoc;
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("TE_SEM-I", asList(new BasicDBObject("Subject_name","TOC").append("Score", ttoc),new BasicDBObject("Subject_name", "DCWSN").append("Score", tdcwsn), 
                        new BasicDBObject("Subject_name", "CF&CA").append("Score", tcfca), new BasicDBObject("Subject_name", "DBMSA").append("Score", tdbmsa)
                        , new BasicDBObject("Subject_name", "OSD").append("Score", tosd)))));
                
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("TE-SEM-I-total",total )));

                JOptionPane.showMessageDialog(this, "Marks Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter valid data in all fields", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        }
        else
            JOptionPane.showMessageDialog(this, "Invalid operation", "Invalid Operation", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_tesem1updbtnActionPerformed

    private void besem1updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_besem1updbtnActionPerformed
        
        if(year.equals("BE")){
            try{
                MongoClient client = new MongoClient("localhost", 27017);
                DB db = client.getDB("StudentProgressTracking");
                DBCollection academic = db.getCollection("academics");

                bimgp = Integer.parseInt(beimgp.getText());
                bcndm = Integer.parseInt(becndm.getText());
                bacp = Integer.parseInt(beacp.getText());
                bdmta = Integer.parseInt(bedmta.getText());
                bes = Integer.parseInt(bees.getText());
                total = bimgp+bcndm+bacp+bdmta+bes;
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("BE_SEM-I", asList(new BasicDBObject("Subject_name","IMG-Processing").append("Score", bimgp),new BasicDBObject("Subject_name", "CNDM").append("Score", bcndm), 
                        new BasicDBObject("Subject_name", "ACP").append("Score", bacp), new BasicDBObject("Subject_name", "DMTA").append("Score", bdmta)
                        , new BasicDBObject("Subject_name", "ES").append("Score", bes)))));
                
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("BE-SEM-I-total",total )));

                JOptionPane.showMessageDialog(this, "Marks Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter valid data in all fields", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        }
        else
            JOptionPane.showMessageDialog(this, "Invalid operation", "Invalid Operation", JOptionPane.ERROR_MESSAGE);
        
        
    }//GEN-LAST:event_besem1updbtnActionPerformed

    private void fesem2updtbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fesem2updtbtn1ActionPerformed
        
        if(year.equals("FE") || year.equals("SE") || year.equals("TE") || year.equals("BE")){
            try{
                fchem = Integer.parseInt(fechem.getText());
                fm2 = Integer.parseInt(fem2.getText());
                felectronics = Integer.parseInt(feelectronics.getText());
                fegr2 = Integer.parseInt(fegraph2.getText());
                fmechanics = Integer.parseInt(femech.getText());
                total = fchem+fm2+felectronics+fegr2+fmechanics;
                MongoClient client = new MongoClient("localhost", 27017);
                DB db = client.getDB("StudentProgressTracking");
                DBCollection academic = db.getCollection("academics");

                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("FE_SEM-II", asList(new BasicDBObject("Subject_name","MII").append("Score", fm2),new BasicDBObject("Subject_name", "Chemistry").append("Score", fchem), 
                        new BasicDBObject("Subject_name", "Mechanics").append("Score", fmechanics), new BasicDBObject("Subject_name", "Electronics").append("Score", felectronics)
                        , new BasicDBObject("Subject_name", "EGR-II").append("Score", fegr2)))));
                
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("FE-SEM-II-total",total )));

                JOptionPane.showMessageDialog(this, "Marks Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);

            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_fesem2updtbtn1ActionPerformed

    private void sesem2updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesem2updbtnActionPerformed
        
        if(year.equals("BE") || year.equals("SE") || year.equals("TE")){
            try{
                MongoClient client = new MongoClient("localhost", 27017);
                DB db = client.getDB("StudentProgressTracking");
                DBCollection academic = db.getCollection("academics");


                scgg = Integer.parseInt(secgg.getText());
                sco = Integer.parseInt(seco.getText());
                sm3 = Integer.parseInt(sem3.getText());
                smit = Integer.parseInt(semit.getText());
                soomp = Integer.parseInt(seoomp.getText());
                total = scgg+sco+sm3+smit+soomp;
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("SE_SEM-II", asList(new BasicDBObject("Subject_name","MIII").append("Score", sm3),new BasicDBObject("Subject_name", "OOMP").append("Score", soomp), 
                        new BasicDBObject("Subject_name", "MIT").append("Score", smit), new BasicDBObject("Subject_name", "CGG").append("Score", scgg)
                        , new BasicDBObject("Subject_name", "CO").append("Score", sco)))));
                
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("SE-SEM-II-total",total )));

                JOptionPane.showMessageDialog(this, "Marks Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter valid data in all fields", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        }
        else
            JOptionPane.showMessageDialog(this, "Invalid operation", "Invalid Operation", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_sesem2updbtnActionPerformed

    private void tesem2updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesem2updbtnActionPerformed
        if(year.equals("BE") || year.equals("TE")){
            try{
                MongoClient client = new MongoClient("localhost", 27017);
                DB db = client.getDB("StudentProgressTracking");
                DBCollection academic = db.getCollection("academics");

                tcn = Integer.parseInt(tecn.getText());           
                tdspa = Integer.parseInt(tedspa.getText());
                tpcdp = Integer.parseInt(tepcdp.getText());
                tsoftware = Integer.parseInt(tesofte.getText());            
                teos = Integer.parseInt(teeos.getText());
                total = tcn+tdspa+tpcdp+tsoftware+teos;
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("TE_SEM-II", asList(new BasicDBObject("Subject_name","PCDP").append("Score", tpcdp),new BasicDBObject("Subject_name", "EOS").append("Score", teos), 
                        new BasicDBObject("Subject_name", "CN").append("Score", tcn), new BasicDBObject("Subject_name", "Soft.Engg").append("Score", tsoftware)
                        , new BasicDBObject("Subject_name", "DSPA").append("Score", tdspa)))));
                
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("TE-SEM-II-total",total )));

                JOptionPane.showMessageDialog(this, "Marks Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter valid data in all fields", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        }
        else
            JOptionPane.showMessageDialog(this, "Invalid operation", "Invalid Operation", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_tesem2updbtnActionPerformed

    private void besem2updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_besem2updbtnActionPerformed
       
        if(year.equals("BE")){
            try{
                MongoClient client = new MongoClient("localhost", 27017);
                DB db = client.getDB("StudentProgressTracking");
                DBCollection academic = db.getCollection("academics");

                bmc = Integer.parseInt(bemc.getText());
                bwt = Integer.parseInt(bewt.getText());
                bcloud = Integer.parseInt(becloudc.getText());
                bcs = Integer.parseInt(becs.getText());
                bma = Integer.parseInt(bema.getText());
                total = bmc+bwt+bcloud+bcs+bma;
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("BE_SEM-II", asList(new BasicDBObject("Subject_name","MC").append("Score", bmc),new BasicDBObject("Subject_name", "WT").append("Score", bwt), 
                        new BasicDBObject("Subject_name", "Cloud Computing").append("Score", bcloud), new BasicDBObject("Subject_name", "ECS").append("Score", becs)
                        , new BasicDBObject("Subject_name", "MA").append("Score", bma)))));
                
                academic.update(new BasicDBObject("Student_ID",rollno), new BasicDBObject("$set", new BasicDBObject("BE-SEM-II-total",total )));

                JOptionPane.showMessageDialog(this, "Marks Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter valid data in all fields", "Oops", JOptionPane.ERROR_MESSAGE);
        }
        }
        else
            JOptionPane.showMessageDialog(this, "Invalid operation", "Invalid Operation", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_besem2updbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beacp;
    private javax.swing.JTextField becloudc;
    private javax.swing.JTextField becndm;
    private javax.swing.JTextField becs;
    private javax.swing.JTextField bedmta;
    private javax.swing.JTextField bees;
    private javax.swing.JTextField beimgp;
    private javax.swing.JTextField bema;
    private javax.swing.JTextField bemc;
    private javax.swing.JButton besem1updbtn;
    private javax.swing.JButton besem2updbtn;
    private javax.swing.JTextField bewt;
    private javax.swing.JTextField fechem;
    private javax.swing.JTextField fecivil;
    private javax.swing.JTextField feelectrical;
    private javax.swing.JTextField feelectronics;
    private javax.swing.JTextField fegraph1;
    private javax.swing.JTextField fegraph2;
    private javax.swing.JTextField fem1;
    private javax.swing.JTextField fem2;
    private javax.swing.JTextField femech;
    private javax.swing.JTextField fephy;
    private javax.swing.JButton fesem1updtbtn;
    private javax.swing.JButton fesem2updtbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField secgg;
    private javax.swing.JTextField seco;
    private javax.swing.JTextField sedeld;
    private javax.swing.JTextField seds;
    private javax.swing.JTextField sedsps;
    private javax.swing.JTextField sem3;
    private javax.swing.JTextField sema;
    private javax.swing.JTextField semit;
    private javax.swing.JTextField seoomp;
    private javax.swing.JTextField seosa;
    private javax.swing.JButton sesem1updbtn;
    private javax.swing.JButton sesem2updbtn;
    private javax.swing.JTextField tecfca;
    private javax.swing.JTextField tecn;
    private javax.swing.JTextField tedbmsa;
    private javax.swing.JTextField tedcwsn;
    private javax.swing.JTextField tedspa;
    private javax.swing.JTextField teeos;
    private javax.swing.JTextField teosd;
    private javax.swing.JTextField tepcdp;
    private javax.swing.JButton tesem1updbtn;
    private javax.swing.JButton tesem2updbtn;
    private javax.swing.JTextField tesofte;
    private javax.swing.JTextField tetoc;
    // End of variables declaration//GEN-END:variables
}
